module.exports = {
  SALT_ROUNDS: +process.env.SALT_ROUNDS,
  SALT_ENV: process.env.SALT_CONSTANT,
  JWT_ACCESS_HASH_KEY: process.env.JWT_ACCESS_HASH_KEY,
  JWT_REFRESH_HASH_KEY: process.env.JWT_REFRESH_HASH_KEY,
  MAIL_GUN_API_KEY: process.env.MAIL_GUN_API_KEY,
  APP_URL: process.env.APP_URL,
  PUBLIC_BUCKET_NAME: process.env.PUBLIC_BUCKET_NAME,
  SERVICE_ACCOUNT_CREDENTIALS: process.env.SERVICE_ACCOUNT_CREDENTIALS,
};
